export const SIGN_IN = "Sign In";
export const SIGN_UP = "Sign Up";
export const MANAGE = "Manage";
export const GENERAL = "General";
export const ADD = "Add";
export const EDIT = "Edit";
export const CURRENT_PROFILE_ID = "currentProfileId";
export const CURRENT_USER_ID = "currentUserId";
export const TYPE_MOVIES = "movies";
export const TYPE_TV_SHOWS = "tvshows"